name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
      - 'feature-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Optionally, add steps to run tests here
    # - name: Run Tests
    #   run: |
    #     python -m unittest discover -s tests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Render CLI
      run: npm install -g render-cli

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }}
